### ISSUE TITLE
Add possibility to change the font size of the day number, day name and month name

### ISSUE THREAD

**Issue by forbroteam** [Mulham-Raee/Horizontal-Calendar#10]
Hello @Mulham-Raee 

It would be nice to have a possibility to change the font size of the day number, day name and month name.
Customize it directly inside the layout or programmatically.

What do you think about that addition, I am happy to open up a PR for it.

Regards!

**Comment by Mulham-Raee** [comment]
Hello @forbroteam 

Yes, it would be a good feature to add, would be helpful if you can open up a Pull request for it.

Regards

**Comment by Mulham-Raee** [comment]
Pull request #11
