### ISSUE TITLE
Failed to set default date in java

### ISSUE THREAD

**Issue by elmokadim** [Mulham-Raee/Horizontal-Calendar#12]
startDate & endDate are exists but what about set default date I can't do it
selectDate() not working for me

**Comment by adin234** [comment]
try using
```java
HorizontalCalendar horizontalCalendar = HorizontalCalendar.Builder.build(); //initialize here
Date start = new Date(/*some epoch*/);
horizontalCalendar.post(new Runnable() {
    @Override
    public void run() {
        horizontalCalendar.selectDate(start, true);
    }
});
```

the idea is put the selector in `post` as a runnable to be run when the calendar is fully initialized

**Comment by elmokadim** [comment]
Thanks. It worked as charm.

**Comment by KarthikPugal86** [comment]
Hi Mulhum,

final Calendar defaultDate = Calendar.getInstance();
defaultDate.add(Calendar.MONTH, -1);
defaultDate.add(Calendar.DAY_OF_WEEK, +3);

 horizontalCalendar.post(new Runnable() {
            @Override
            public void run() {
                Log.i("MainActivity", "defaultDate "+defaultDate.getTime());
                horizontalCalendar.selectDate(defaultDate.getTime(), true);
            }
        });

But response is two date is selected. How can i fix this issue?
Reason : 
int selectedItemPosition = horizontalCalendarView.getPositionOfCenterItem();
Start Date & Default Date 1st time loading centerItemPostion.

[ScreenShot](https://www.dropbox.com/s/jgzhf61ke0uh131/horizontalcalendar.jpeg?dl=0)
