### ISSUE TITLE
How can i disable click & horizontal scroll listener?

### ISSUE THREAD

**Issue by KarthikPugal86** [Mulham-Raee/Horizontal-Calendar#14]
HI Mulham,

Builder Class I done enable for click listener
public Builder setEnable(boolean enable){
            this.enable = enable;
            return this;
        }

HorizontalCalendarAdapter class I modified.

if(enable) {
            holder.rootView.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    //int stepX = getStepX(v);
                    Date date = datesList.get(holder.getAdapterPosition());

                    if (!date.before(horizontalCalendar.getDateStartCalendar())
                            && !date.after(horizontalCalendar.getDateEndCalendar())) {
                        //horizontalCalendarView.smoothScrollBy(stepX, 0);
                        horizontalCalendarView.setSmoothScrollSpeed(HorizontalLayoutManager.SPEED_SLOW);
                        horizontalCalendar.centerCalendarToPosition(holder.getAdapterPosition());
                    }
                }
            });

            holder.rootView.setOnLongClickListener(new View.OnLongClickListener() {
                @Override
                public boolean onLongClick(View v) {
                    Date date = datesList.get(holder.getAdapterPosition());
                    HorizontalCalendarListener calendarListener = horizontalCalendar.getCalendarListener();
                    if (calendarListener != null && !date.before(horizontalCalendar.getDateStartCalendar())
                            && !date.after(horizontalCalendar.getDateEndCalendar())) {
                        return calendarListener.onDateLongClicked(date, holder.getAdapterPosition());
                    }
                    return false;
                }
            });
        }

But I cannot stop Horizontal Scroll Listener. Because My project features requirements. Please help me out from my project issue!

Thanks in advance.

**Comment by Mulham-Raee** [comment]
Hello @KarthikPugal86 

I don't really understand what you want to do.
Do you want to disable clicks? please try to explain you requirements better.

Regards
Mulham

**Comment by KarthikPugal86** [comment]
Do you want to disable clicks?
yes want to disable scroll listener.

**Comment by Mulham-Raee** [comment]
Why would you like to disable scroll listener? you don't have to listen changes!
just don't implement it in your code

**Comment by Mulham-Raee** [comment]
No explanation provided!
