### ISSUE TITLE
How can i fix next date is default selection?

### ISSUE THREAD

**Issue by KarthikPugal86** [Mulham-Raee/Horizontal-Calendar#15]
@Mulham-Raee

final Calendar defaultDate = Calendar.getInstance();
defaultDate.add(Calendar.MONTH, -1);
defaultDate.add(Calendar.DAY_OF_WEEK, +3);

horizontalCalendar.post(new Runnable() {
@Override
public void run() {
Log.i("MainActivity", "defaultDate "+defaultDate.getTime());
horizontalCalendar.selectDate(defaultDate.getTime(), true);
}
});

But response is two date is selected. How can i fix this issue?
Reason :
int selectedItemPosition = horizontalCalendarView.getPositionOfCenterItem();
Current Date & Default Date 1st time loading centerItemPostion.

[ScreenShot](https://www.dropbox.com/s/jgzhf61ke0uh131/horizontalcalendar.jpeg?dl=0)

**Comment by Mulham-Raee** [comment]
In your builder set `selectToday(false)`

**Comment by KarthikPugal86** [comment]
Thanks its working fine.
.centerToday(false)
.build();

**Comment by Mulham-Raee** [comment]
Hello @KarthikPugal86,

I have implemented you requested feature to selected a default date, please use the latest version 1.1.5, and check [README](https://github.com/Mulham-Raee/Horizontal-Calendar/blob/master/README.md) for more information on how to use.

Best Regards,
Mulham

**Comment by KarthikPugal86** [comment]
Thanks a lot, its working good.
