### ISSUE TITLE
Change date call onDateSelected() twice

### ISSUE THREAD

**Issue by elmokadim** [Mulham-Raee/Horizontal-Calendar#17]
When changing date onDateSelected() called twice, once with old date and once more with new date.
why this behavior  happens?

Clarification: It happens only when scrolling calendar and working right when clicking

**Comment by Mulham-Raee** [comment]
Hello @elmokadim 

I can't seem to reproduce the problem you are talking about, try using the latest version:
`compile 'devs.mulham.horizontalcalendar:horizontalcalendar:1.1.0'` 
if you are not and try one more time.

Regards.
Mulham
