### ISSUE TITLE
Unable to selectDate

### ISSUE THREAD

**Issue by vinjex** [Mulham-Raee/Horizontal-Calendar#19]
I'm having problem changing the selected date. Basically I have a button that should select "tomorrow"
`public void onClick(View v) {
                Calendar tomorrow = Calendar.getInstance();
                tomorrow.add(Calendar.DAY_OF_MONTH, 1);
                horizontalCalendar.selectDate(tomorrow);
            }`
I never used Calendar or Date before so maybe is just an error in my comprehension. 
This is the  Horizontal Calendar build:
`final HorizontalCalendar horizontalCalendar = new HorizontalCalendar.Builder(view, R.id.calendarView)
                .startDate(startDate.getTime())
                .endDate(endDate.getTime())
                .showMonthName(false)
                .build();`

**Comment by Mulham-Raee** [comment]
Hello @vinjex 

Is your problem solved?

**Comment by vinjex** [comment]
@Mulham-Raee 
Yes, there was a problem with some of my code, after solving that your calendar worked as intended. By the way thank you for your work, it speeded up my project a lot.

**Comment by Mulham-Raee** [comment]
Glad it helped you in your project, if you don't mind sending me a link of your app, I would be happy to feature it here.

**Comment by vinjex** [comment]
Sure, as soon as I upload to it to the play store I'll send you a link. The repo is currently private because of my workplace's rules, so I can't show it to you for the moment.
