### ISSUE TITLE
Can i disable the month to be displayed

### ISSUE THREAD

**Issue by preyesm** [Mulham-Raee/Horizontal-Calendar#2]
@Mulham-Raee, I have the current month being displayed on the toolbar and in the library the month name above every date becomes redundant, can i remove it without adopting the library. If youd could provide this option as for date and day, it would be of great help

**Comment by Mulham-Raee** [comment]
@preyesm this feature is not supported at the moment, but I will take into consideration in the next release.
For now you can clone the repo and adopt it to your needs.

**Comment by preyesm** [comment]
@Mulham-Raee any approximate dates for the next release?

**Comment by Mulham-Raee** [comment]
@preyesm possibly in 1 to 2 months as I have currently other things to do.

**Comment by Mulham-Raee** [comment]
Hello @preyesm ,

Your requested features are now live, check **version 1.1.0**.
Thanks!
