### ISSUE TITLE
Reset Horizontal-Calendar settings 

### ISSUE THREAD

**Issue by ritesh94** [Mulham-Raee/Horizontal-Calendar#23]
I want to reinitialize the HorizontalCalendar every time I select Spinner item.

But I get below error: 
java.lang.IllegalStateException: An instance of OnFlingListener already set.

For following code :

```
 sp_bkapt_select_pgm.setOnItemSelectedListener(new AdapterView.OnItemSelectedListener() {
            @Override
            public void onItemSelected(AdapterView<?> adapterView, View view, int i, long l) {
                System.out.println("I m setSpinner : " + adapterView.getItemAtPosition(i));

    horizontalCalendar_viewSch = new HorizontalCalendar.Builder(Activity_ViewAppointmentsSchedule.this, R.id.horizontalCalendar_viewSch)
                                .startDate(actualStrtDate)
                                .endDate(endDate)
                                .datesNumberOnScreen(5)
                                .dayNameFormat("EEE")
                                .dayNumberFormat("dd")
                                .monthFormat("MMM")
                                .showDayName(true)
                                .showMonthName(true)
                                .defaultSelectedDate(strtDate)
                                .textColor(Color.parseColor("#191919"), Color.WHITE)
                                .build();       


            }

            @Override
            public void onNothingSelected(AdapterView<?> adapterView) {

            }
        });
```

**Comment by Mulham-Raee** [comment]
Hello @ritesh94 

Unfortunately HorizontalCalendar can't be initialized more than once!
What is your use case? why do you want to reinitialize it every time?

**Comment by ritesh94** [comment]
Hi @Mulham-Raee 

This is how I am reinitializing the horizontalCalendar

```

HorizontalCalendar horizontalCalendar_viewSch;

private void resetData(){
 if (horizontalCalendar_viewSch != null) {
                            horizontalCalendar_viewSch.setCalendarListener(null);
                        }


                        horizontalCalendar_viewSch = new HorizontalCalendar.Builder(Activity_ViewAppointmentsSchedule.this, R.id.horizontalCalendar_viewSch)
                                .startDate(actualStrtDate)
                                .endDate(endDate)
                                .datesNumberOnScreen(5)
                                .dayNameFormat("EEE")
                                .dayNumberFormat("dd")
                                .monthFormat("MMM")
                                .showDayName(true)
                                .showMonthName(true)
                                .defaultSelectedDate(strtDate)
                                .textColor(Color.parseColor("#191919"), Color.WHITE)
                                .build();

// and set the calendarListener here 

}
```

**Comment by AshaChaparala** [comment]
I want to update dates based on selected month and year,so i need o reinitalize when ever month and year selected

**Comment by Mulham-Raee** [comment]
Hello @AshaChaparalal,

This is perfectly a valid use case, but unfortunately it is not supported at the moment, I will be adding it for sure in the next version.

Regards.

**Comment by Mulham-Raee** [comment]
@AshaChaparala @ritesh94 

This feature has been implemented in version `1.3.0`,  please check https://github.com/Mulham-Raee/Horizontal-Calendar#reconfiguration, for more information.

**Comment by Danish1111** [comment]
I am getting this issue  **java.lang.IllegalStateException: An instance of OnFlingListener already set**.    
when i am initializing my horizontalCalendar in fragment.  Please explain how to solve it step by step

**Comment by piotrek1543** [comment]
@Danish1111 Move initialization like this ```    horizontalCalendar_viewSch = new HorizontalCalendar.Builder(Activity_ViewAppointmentsSchedule.this, R.id.horizontalCalendar_viewSch)
                                .startDate(actualStrtDate)
                                .endDate(endDate)
                                .datesNumberOnScreen(5)
                                .dayNameFormat("EEE")
                                .dayNumberFormat("dd")
                                .monthFormat("MMM")
                                .showDayName(true)
                                .showMonthName(true)
                                .defaultSelectedDate(strtDate)
                                .textColor(Color.parseColor("#191919"), Color.WHITE)
                                .build();``` to `onCreate` instead of `onViewCreated`

**Comment by Chirag-02** [comment]
@Mulham-Raee  @AshaChaparala 
I am facing same issue :- I want to update dates based on selected month and year,so i need to reinitialize when ever month and year selected
getting Exception -> An instance of OnFlingListener already set.

Please help to resolve this in fragment and  how to use horizontalCalender.refresh() in fragment?
