### ISSUE TITLE
Is there a way to highlight particular dates in the tabs?

### ISSUE THREAD

**Issue by jsingh-jasmeet** [Mulham-Raee/Horizontal-Calendar#25]
I was wondering if there is a way to use some markers or such thing to highlight a particular date, such as when the user has events on that date? For example, I would like to achieve something of this sort with the calendar (look at the right screen):

![alt tag](http://i.imgur.com/JZIOqmp.png)

Is there a way to customize the calendar to achieve that?

**Comment by MarkAguirre26** [comment]
Same question here too..

**Comment by jcarlos79t** [comment]
Good question. :)

**Comment by alliejc** [comment]
+1

**Comment by PedroNieto** [comment]
+1

**Comment by alejocba04** [comment]
+1 !!!!

**Comment by Mulham-Raee** [comment]
![test](https://user-images.githubusercontent.com/11375280/34957055-3364d604-fa2c-11e7-8007-b5651dd40e44.png)

Feature is implemented in version `1.3.2`, check https://github.com/Mulham-Raee/Horizontal-Calendar#events for more details.
