### ISSUE TITLE
Fix bug with selection previous item when select day before current

### ISSUE THREAD

**Issue by Niks0707** [Mulham-Raee/Horizontal-Calendar#30]
For fix bug with selection previous item when select day before current need change next method in HorizontalCalendarView:
public int getPositionOfCenterItem() {
        int numberOfDatesOnScreen = horizontalCalendar.getNumberOfDatesOnScreen();
        int firstVisibilePosition = getLayoutManager().findFirstCompletelyVisibleItemPosition();
        if (firstVisibilePosition == -1) {
            return -1;
        }
        return firstVisibilePosition + (numberOfDatesOnScreen / 2);
    }

To:

public int getPositionOfCenterItem() {
        int numberOfDatesOnScreen = horizontalCalendar.getNumberOfDatesOnScreen();
        int firstVisiblePosition = getLayoutManager().findFirstVisibleItemPosition();
        if (firstVisiblePosition == -1) {
            return -1;
        }
        return firstVisiblePosition + (numberOfDatesOnScreen / 2);
    }

**Comment by mrukarayan** [comment]
Nice...this works for me

**Comment by JJSarrasin** [comment]
By doing this, you broke the selectDate method in large screen.

When does your problem occurs exactly ? I could not reproduce in my app.
