### ISSUE TITLE
Screen Orientation?

### ISSUE THREAD

**Issue by Widiyanto** [Mulham-Raee/Horizontal-Calendar#31]

**Comment by Mulham-Raee** [comment]
What about it? please be more specific when you open an issue!

**Comment by Widiyanto** [comment]
When screen orientation, date selected back to today

**Comment by jcarlos79t** [comment]
Same problem as solving this? please

**Comment by Mulham-Raee** [comment]
Hello,

This is not the job of the library, if you want to save you selection, you have to save the state of your Activity and re select the date once the Activity is recreated after orientation change.
