### ISSUE TITLE
Cannot select default date once scrolled to another date

### ISSUE THREAD

**Issue by raviPradhan** [Mulham-Raee/Horizontal-Calendar#33]
When the activity opens first today's default date is selected. Once I scroll and try to come back to today's default date, I cannot do so. My problem will be shown in this video:

https://drive.google.com/open?id=0B8wL31ixEiQybDQwVFlUQW44OFU

It seems that it works fine when I set number of items to be shown as 4 ".datesNumberOnScreen(4)" i.e. when the numbers are even. The problem occurs when I give numbers as 5, 3.

**Comment by Mulham-Raee** [comment]
Can't reproduce this bug, please use the latest version `1.2.2` and try again.
