### ISSUE TITLE
Select a date and calendarListener.onDateSelected() callback two times

### ISSUE THREAD

**Issue by lmdiloveu** [Mulham-Raee/Horizontal-Calendar#34]
Select a date and calendarListener.onDateSelected() callback two times . Every time a date is selected, I need to access the network interface once , causes my code to access the two network interface，how to fix it?

**Comment by tonyannick** [comment]
same for me....... the date is selected itself in oncreate method and make a network request.

**Comment by Mulham-Raee** [comment]
possible duplicate of #28
