### ISSUE TITLE
How to set the min and max dates range to be largest as possible?

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Mulham-Raee/Horizontal-Calendar#45]
Currently I use this:

        Calendar startDate = Calendar.getInstance();
        startDate.setTime(new Date(0L));
        Calendar endDate = Calendar.getInstance();
        endDate.add(Calendar.YEAR, 120);

        horizontalCalendar = new HorizontalCalendar.Builder(this, R.id.calendarView)
                .startDate(startDate.getTime())
                .endDate(endDate.getTime())
                ...

but what's the largest range this library support?

**Comment by Mulham-Raee** [comment]
Hello @AndroidDeveloperLB 

The library doesn't specify any limits for the date range, as it is built on top of RecyclerView.
Unless RecyclerView has any limits, the only limit is how much your device can handle.

**Comment by Mulham-Raee** [comment]
It doesn't seem that RecyclerView has any limits, it depends only on the device capabilities.

**Comment by AndroidDeveloperLB** [comment]
I didn't say the RecyclerView has limits. I asked about the dates themselves.
The RecyclerView does have limits BTW, by the adapter:

     int getItemCount()

so the max is Integer.MAX_VALUE-1 , which is a very large number.

**Comment by Mulham-Raee** [comment]
Dear @AndroidDeveloperLB 

Integer.MAX_VALUE is no limit, it is simply the largest Integer out there, I was talking about real limits defined in the RecyclerView which there is not.
If you are asking about the dates limit, again it doesn't depends on the library, it is simply java Dates objects. so you need to check Java Docs for that.

**Comment by AndroidDeveloperLB** [comment]
Can you please let me know what is the min&max limit?
If it's really 1970 for min, maybe it's better this library should use something else instead of Date? Maybe Calendar is better?

**Comment by Mulham-Raee** [comment]
1970-01-01 is the reference date used by `java.util.Date`, since `java.util.Date` stores dates as long (milliseconds) and long is a signed 64-bit integer, you can expect `java.util.Date` to cover about 290 million years before and after the reference date.

**Comment by AndroidDeveloperLB** [comment]
So I can use before 1970?
Say, a 120 years before today, and 120 years after?

**Comment by Mulham-Raee** [comment]
Yes theoretically you can!
