### ISSUE TITLE
Bug: goToday not immediate enough

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Mulham-Raee/Horizontal-Calendar#46]
### Expected Behavior / Goal
> To go straight to the given date, by using:
horizontalCalendar.goToday(true);

### Actual Behavior
> It doesn't always go so quickly to there. Depends on device or Android version

### Steps to Reproduce the Problem (sample code if possible)
  >1. Make the date range large. I used this:
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/45
  >2. scroll a lot. 
  >3. Choose to go to current day.

### Specifications

 > - Android Version:
6.0.1 on OnePlus 2
 > - Horizontal-Calendar Version:
1.1.8

See how slow it can be (took about 2 seconds to reach there) :
[VID_20171024_121150 (1).zip](https://github.com/Mulham-Raee/Horizontal-Calendar/files/1410214/VID_20171024_121150.1.zip)

**Comment by AndroidDeveloperLB** [comment]
In fact, this issue exists right on initialization of the view.
At first it shows some date range, and after it found out which date to go to by default, it scrolls to it.
Here:

[VID_20171024_122327 (1).zip](https://github.com/Mulham-Raee/Horizontal-Calendar/files/1410251/VID_20171024_122327.1.zip)

**Comment by Mulham-Raee** [comment]
Thanks for pointing this out, this was not considered while testing as this library was not intended to display such a large range.
I will be looking into it.

**Comment by AndroidDeveloperLB** [comment]
I've tried finding out the reason for this. I still can't find it.
What I did find is various things that can be optimized.
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/48
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/47

I've also found that in the adapter, you can avoid setting some parameters over and over in the onBindViewHolder, and instead do them once in the onCreateViewHolder.
Such parameters are text size, and text color.
The text size doesn't change, so no need to set it over and over.
The text color can be a color-selector, so it will be determined by the condition that you've used there.

**Comment by AndroidDeveloperLB** [comment]
I think I've found one reason for this lag:

```
    public int positionOfDate(Date date) {
        int position = -1;
        for (int i = 0; i < mListDays.size(); i++) {
            if (isDatesDaysEquals(date, mListDays.get(i))) {
                position = i;
                break;
            }
        }
        return position;
    }
```

This is called from "selectDate" function, yet instead of finding the date efficiently, it goes one after another.
A possible solution is using binary search. It's even easier because there is a function for it.

But an even better solution, is to just have the difference in days between the first item, and the one you are provided.

**Comment by AndroidDeveloperLB** [comment]
Seems like this is really the reason.
After removing the part that it has loaded all of the dates into a list, and using only pure calculations, it works very well.
I've changed the sample to show a range of 100 years before current date, and 100 years after current date.

Sadly, my current code has a little bug currently, that occurs because the starting date of the adapter is the really one that is first shown on the list, yet can't be selected. Same for the ending date.
It will work, but you can't go to the selection of the most left and most right items. 

I'm sure you can fix this issue easily.

It does however work with scrolling quickly to whichever date you wish, and it supports any date range you wish, without any special usage of memory.

Here's the new project :
[Horizontal-Calendar.zip](https://github.com/Mulham-Raee/Horizontal-Calendar/files/1412525/Horizontal-Calendar.zip)

I haven't fixed the lag issue yet. 

Hope this helps.

**Comment by AndroidDeveloperLB** [comment]
@Mulham-Raee  Did you look at the code?
You saw that it works?
Why close this?

**Comment by Mulham-Raee** [comment]
![capture](https://user-images.githubusercontent.com/11375280/32070525-f769091a-ba8c-11e7-9126-21c4d2b3b10e.PNG)
I closed this in a commit, because I solved the problem!

**Comment by AndroidDeveloperLB** [comment]
How did you solve it?

**Comment by Mulham-Raee** [comment]
Check the changes in the commit.

**Comment by AndroidDeveloperLB** [comment]
I have. This is why I wrote "found what you did"
