### ISSUE TITLE
Request: avoid caching of dates

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Mulham-Raee/Horizontal-Calendar#47]
I've noticed that before the view is used, an AsyncTask is executed that saves all dates in the range:

        @Override
        protected Void doInBackground(Void... params) {
            //ArrayList of dates is set with all the dates between
            //start and end date
            GregorianCalendar calendar = new GregorianCalendar();

            calendar.setTime(dateStartCalendar);
            calendar.add(Calendar.DATE, -(numberOfDatesOnScreen / 2));
            Date dateStartBefore = calendar.getTime();
            calendar.setTime(dateEndCalendar);
            calendar.add(Calendar.DATE, numberOfDatesOnScreen / 2);
            Date dateEndAfter = calendar.getTime();

            Date date = dateStartBefore;
            while (!date.after(dateEndAfter)) {
                mListDays.add(date);
                calendar.setTime(date);
                calendar.add(Calendar.DATE, 1);
                date = calendar.getTime();
            }

            return null;
        }

This is a bad thing:
1. It takes time till the view is ready, for a view that simply needs to show dates.
2. It can take a huge amount of Date items. In my case, that I wanted to show a large range, it takes at least 60K of Date objects.
All of this in memory.

Instead of this, the view should immediately go to the correct date. 
The calculation can be done on the UI thread, in the onBindViewHolder callback, by comparing the current item position to the pivot date (the date you started from, or the start date).

**Comment by AndroidDeveloperLB** [comment]
Here's a possible way to avoid the caching:

        @JvmStatic private val MS_IN_24_HOURS = (1000 * 60 * 60 * 24).toLong()

        @JvmStatic
        fun getWhole24DayDifference(time1: Long, time2: Long): Long {
            val diff = Math.abs(time1 - time2)
            return diff / MS_IN_24_HOURS
        }

        val startDate=...
        val endDate=...
        val numberOfDateItems = getWhole24DayDifference(endDate.time, startDate.time)


In the adapter:

                val cal = Calendar.getInstance()

                override fun getItemCount(): Int {
                    return numberOfDateItems.toInt()
                }

                fun getItem(pos: Int): Date {
                    cal.time = startDate
                    cal.add(Calendar.DATE, pos)
                    return cal.time
                }

**Comment by Mulham-Raee** [comment]
Again this library was not intended to display large range of dates, therefore performance was not the focus rather simplicity.
It is true that storing a large number of dates is not optimal, but what you are suggesting requires a lot of changes in the structure of the library.
If you would like to contribute and get this enhancement fast, please feel free to open a pull-request, otherwise it will take me sometime to do it, as I have some other bugs to fix.

Regards.

**Comment by AndroidDeveloperLB** [comment]
But why was it important to save all the dates? It's very fast to calculate the date to show, per each item...

I hope I will have time to check it out at home. Do you mind that I remove unused functions, though?

**Comment by AndroidDeveloperLB** [comment]
I've put a full solution to this issue here:
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/46#issuecomment-339133571

There is no caching of dates whatsoever. Everything is instant. There is no huge list of dates.
Please check it out.

**Comment by Mulham-Raee** [comment]
@AndroidDeveloperLB 

Implemented, thank for your contribution!
