### ISSUE TITLE
Request: avoid useless calls to notifyDataSetChanged when scrolling

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Mulham-Raee/Horizontal-Calendar#48]
You should only refresh the views of the RecyclerView when needed.

Currently what you do is this:

        @Override
        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
            //On Scroll, agenda is refresh to update background colors
            post(new Runnable() {
                @Override
                public void run() {
                    mCalendarAdapter.notifyDataSetChanged();
                }
            });
            ...
        }

First, the "post" is not needed because you are already on the UI thread.
Second, on most cases, when scrolling, the selected item doesn't change, so it's not needed to call notifyDataSetChanged.
Instead, you can check if the previously selected item is the same as the current one, and only if they are not, call notifyDataSetChanged.

Another approach that I'm not sure if is the best, is to do it on the onBindViewHolder: whenever you reach another cell, you can check if the selected item has changed, and if so, go directly on all ViewHolders and update their state.

**Comment by Mulham-Raee** [comment]
This is required to animate the change of selected date while scrolling.
otherwise you will get not visual effects about the changes during the scroll, you can consider it cosmetic.
I might add an option to turn this feature off in the future, but it is totally valid.

**Comment by AndroidDeveloperLB** [comment]
What animations? I see a very simple change of what is selected. 
There are no animations. I can't see animations even on the gif image of the repo.
See:
[device-2017-10-24-162321.zip](https://github.com/Mulham-Raee/Horizontal-Calendar/files/1410967/device-2017-10-24-162321.zip)

**Comment by AndroidDeveloperLB** [comment]
Also, why would this part affect the animations? It will post the exact same event: item X was selected.

**Comment by AndroidDeveloperLB** [comment]
In addition, even if you ignore the part I wrote of notifyDataSetChanged, the onDateSelected isn't called here, even though the selected item has changed during the scrolling, because if you'd call "getSelectedDatePosition" while scrolling, you will get a different value than before the scrolling started.

**Comment by Mulham-Raee** [comment]
Unless you really has test the changes you are proposing, this discussion leads to nothing.
Without the code that you suggest I remove the selector(the little rectangle at the bottom of the selected item) will not update its position while scrolling!

**Comment by AndroidDeveloperLB** [comment]
I have actually tested it, but I can suggest even without testing. It makes sense, and it doesn't need a lot of change to try it. It requires just a very few lines of code.

Here's the change:

```
    private HorizontalCalendarListener calendarListener;
    private final RecyclerView.OnScrollListener onScrollListener = new RecyclerView.OnScrollListener() {
        private int lastSelectedItem = Integer.MIN_VALUE; // new

        @Override
        public void onScrollStateChanged(RecyclerView recyclerView, int newState) {
            if (newState == RecyclerView.SCROLL_STATE_IDLE) {
                //On scroll end, the dateSelect event is call
                //and agenda is center to the good item
                int position = calendarView.getPositionOfCenterItem();
                if (calendarListener != null) {
                    calendarListener.onDateSelected(mListDays.get(position), position);
                }
            }
        }

        @Override
        public void onScrolled(RecyclerView recyclerView, int dx, int dy) {
            final int positionOfCenterItem = calendarView.getPositionOfCenterItem();
            //new part:
            if (lastSelectedItem == Integer.MIN_VALUE || lastSelectedItem != positionOfCenterItem) {
                //On Scroll, agenda is refresh to update background colors
                mCalendarAdapter.notifyDataSetChanged();
                lastSelectedItem = positionOfCenterItem;
            }
            //end of new part
            if (calendarListener != null) {
                calendarListener.onCalendarScroll(calendarView, dx, dy);
            }
        }
    };
```

Here's the result:

[device-2017-10-24-170419.zip](https://github.com/Mulham-Raee/Horizontal-Calendar/files/1411114/device-2017-10-24-170419.zip)


Sadly, it doesn't help much with the lags the scrolling have, so I made a new request here:
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/49

**Comment by Mulham-Raee** [comment]
This little optimizations you are asking for have little to no impact on the actual performance, the only problem here is that you are using a very large range of Dates which makes not sense in an actual use-case in any app.
If you want to contribute to this project there is a bunch of open issues you can close by opening a pull request.

Regards

**Comment by AndroidDeveloperLB** [comment]
The large list is not the cause of performance. It's just more memory that the app uses.
You can try it on a small range too. Even 2 months.
Using a long range isn't a problem. Calendars are supposed to have practically no limit. The sample shows a very small range that can be used in calendar apps, even though the library is supposed to deal with calendars (its name is "Horizontal-Calendar").

**Comment by AndroidDeveloperLB** [comment]
Here, I used the exact sample that's in the repo, without any changes:

![image](https://user-images.githubusercontent.com/5357526/31948596-000ecfae-b8e0-11e7-9b56-7dc24afb77c0.png)

All I did is fast scrolling.

**Comment by Mulham-Raee** [comment]
Yes calendars have limits, take for example Google calendar, you can only scroll down to year 2037 :)
What does the library name have to do with the implementation? NO Horizontal-Calendar doesn't refer that it should deal with Calendar object!

Calendar Definition: 
> a chart or series of pages showing the days, weeks, and months of a particular year, or giving particular seasonal information.

**Comment by AndroidDeveloperLB** [comment]
I can't see your point. Why should a calendar library be limited by dates it can show? Sure it should show a part of the dates possible at a given time, since the screen is limited by resolution, but why, for a scrolling calendar, it should be limited?

And, why do you keep on talking about this, when the topic is about something else: the library updates all of the views of the RecyclerView too many times. 
I've even showed you here that this could be the reason for bad performance of scrolling:
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/49
And this is by using an untouched-code. It's the same exact sample. No large range. 

BTW, Google calendar app allows to scroll from 1970 to 2037. That's about 67 years. 
And, events can be set there from 1900 to 2100. That's about 200 years. 

I'm pretty sure they could have made it much larger, and still not suffer from performance or memory issues on the app. To me it scrolls smoothly, and to that you should try to reach, just as I try.

Developing for smartphones can be a hard work. You have to minimize the memory usage and also strive for best performance you can get.

**Comment by Mulham-Raee** [comment]
I am not the one getting off topic here, I am just replying to your comments!
Again I said nothing about limits, yes theoretically it should have no limits, what I am seeing is that I didn't account for performance issues on large range of Dates because it is not a valid use-case in an Horizontal Calendar ( not a typical Calendar which takes up the entire screen)!

To the point of this issue:
- I have already explained why I am making this call `mCalendarAdapter.notifyDataSetChanged();` to update the selector position which means your issue is invalid it is not "useless".
- Yes it causes minimal performance drop down which you pointed it out here #49, I will be investigating the cause and the solution to this but it is not a priority, unless you have a working solution!

> Developing for smartphones can be a hard work. You have to minimize the memory usage and also strive for best performance you can get.
I am well aware of that, this is still a young project and needs more work :)

**Comment by AndroidDeveloperLB** [comment]
"This little optimizations you are asking for have little to no impact on the actual performance, the only problem here is that you are using a very large range of Dates which makes not sense in an actual use-case in any app."
"what I am seeing is that I didn't account for performance issues on large range of Dates because it is not a valid use-case in an Horizontal Calendar ( not a typical Calendar which takes up the entire screen)!
"
This is something you wrote. The performance that I've seen is on the sample too.
The limit is just a pointless limitation. It doesn't matter how a calendar is shown. It can be horizontal, vertical, circular,... You can't go to the definition of what a calendar is, just to justify this limitation, especially if one of your own examples is Google calendar, which has far larger range of dates.
And, again and again, I tell you: the large range has nothing to do with the performance. 
It could only affect the initialization, but even then, it's very quick.

"I have already explained why I am making this call mCalendarAdapter.notifyDataSetChanged(); to update the selector position which means your issue is invalid it is not "useless".
"
As I wrote, the part that is useless is that you call call it when nothing has changed, which occurs quite a lot in the current code you have. 
The reason that the extra calls are useless, is that for most cases, when you scroll, the selected item stays the same selected item, so there is no need to refresh all views again.
The correct time to call it, is when the selection actually changed, which is the purpose of this call.

"Yes it causes minimal performance drop down which you pointed it out here #49, I will be investigating the cause and the solution to this but it is not a priority, unless you have a working solution!
"
Currently I work on a direct approach, with the very minimal refreshes of views, and only when needed. I hope this will solve this issue. If not, I don't think there could be any better optimization in terms of the adapter. 
The part of "only when needed" is what I wrote to you in the beginning of this thread.

**Comment by Mulham-Raee** [comment]
>  The reason that the extra calls are useless, is that for most cases, when you scroll, the selected item stays the same selected item, so there is no need to refresh all views again.

I think you don't get how `selectedItem` is calculated here, selectedItem is always he item on the center of the screen, thus whenever and wherever you scroll selectedItem will change so the selector must move and selectedItemBackground must be applied etc....

`onScrolled` method is called whenever you reach the next item while scrolling, so your code to save the last slectedItem (center on screen) and compare to the current selectedItem is absolutely redundant!

Please stop talking about limitations, I didn't say that it should have any limitation, I just pointed out that I don't see any valid **use-case** for such a Horizontal Calendar to have  a large range of Dates and there is not, unless you give me a real app with such use-case.
## My library has no limitations, and it will never have!

Also you said :
> the "post" is not needed because you are already on the UI thread.

which is wrong again because you can't change call notifyChanges while the RecylerView calculating its scroll position. that is why I am using `post ` here so the code gets executed after the calculations are done!

**Comment by AndroidDeveloperLB** [comment]
> I think you don't get how selectedItem is calculated here, selectedItem is always he item on the center of the screen, thus whenever and wherever you scroll selectedItem will change so the selector must move and selectedItemBackground must be applied etc....
> 
> onScrolled method is called whenever you reach the next item while scrolling, so your code to save the last slectedItem (center on screen) and compare to the current selectedItem is absolutely redundant!

Incorrect. It's what you did that is redundant. There is no need to call notifyDataSetChanged multiple times after the selection hasn't changed. Take this scenario: you moved a few pixels. A new selection was detected, so you call notifyDataSetChanged  . You moved just one pixel, and the selection is still the same. You still call notifyDataSetChanged . You move another, and still...

And I know why it's in the scroll listener, too.
To show why what you wrote is incorrect, just print to the log, the number of times it calls notifyDataSetChanged , with the currently selected item that is calculated there.

Here's a demonstration :
![image](https://user-images.githubusercontent.com/5357526/31964410-98d945ee-b90c-11e7-97e2-5c95e1ad5b4c.png)

In what I offered, at least it filters out the un-needed calls. 
I've tested my code too again at home. Still works fine. See the calls to notifyDatasetChanged:

![image](https://user-images.githubusercontent.com/5357526/31964602-42c992a2-b90d-11e7-9934-cc44d2e01d84.png)

Also, the "post" is not needed, and you can try it too. I've already tried the changes I wrote. 
Even if it was needed, there is no need to re-create the Runnable instance over and over again. This increases GC, which is a bad thing for RecyclerView being scrolled. You should have used it this way instead:
![image](https://user-images.githubusercontent.com/5357526/31964465-c33b93f0-b90c-11e7-874d-ba5b7dc08afc.png)

"My library has no limitations, and it will never have!"
ok, so please don't say that I'm not supposed to use it with a large range of dates, because it shouldn't have this limitation.

**Comment by Mulham-Raee** [comment]
> Also, the "post" is not needed, and you can try it too. I've already tried the changes I wrote.
It doesn't work without it, please test test test before talking!

I don't know what you are trying to prove here, but your suggested changes will have absolutely 0 effect on the performance.
It is not running on a Nokia, most Android phones now days will not be affected by any of the thing you are trying to change.

**Comment by AndroidDeveloperLB** [comment]
I think on my Nexus 5x, you can see my fix is a bit better. 
It's not the best I think it could be, but it's better.
This time I made a video, of before and after.
Here:

[nexus5x.zip](https://github.com/Mulham-Raee/Horizontal-Calendar/files/1412328/nexus5x.zip)

Note that this is Nexus 5x, with Android O.
The result might be different for older devices with older Android versions, and you should think about it, because the library supports Android 14 and above.
It could also be about the same (as I've shown on OnePlus 2 with Android 6.0.1), because of optimizations done on Android O.

**Comment by AndroidDeveloperLB** [comment]
"It doesn't work without it, please test test test before talking!
"
I didn't write this. You did. And I have tested. On OnePlus 2 with Android 6.0.1, and on my Nexus 5x, which has Android O.

**Comment by Mulham-Raee** [comment]
The thing is I don't see the lag you are experiencing.
Anyway I will integrate your recommendations and some changes of mine to optimize the performance while scrolling.
please move any further discussions here #49

Thanks

**Comment by AndroidDeveloperLB** [comment]
But what do you mean by "it's not running" ?
Also, I've found the reason of the slow scrolling to specific date:
https://github.com/Mulham-Raee/Horizontal-Calendar/issues/46
