### ISSUE TITLE
Cant get the horizontalCalendar.getSelectedDate()

### ISSUE THREAD

**Issue by ibrahim-appgodz** [Mulham-Raee/Horizontal-Calendar#5]
It shows always error while calling horizontalCalendar.getSelectedDate();

**Comment by Mulham-Raee** [comment]
Hello @ibrahim-appgodz ,

I need to know the kind of error you are receiving before I can help you!
Also please post some code snippets, or the steps you made to reproduce this error.

Thanks.

**Comment by Mulham-Raee** [comment]
no respone!

**Comment by ibrahim-appgodz** [comment]
Sorry, I deleted the stack traces of the error. But it was still there. Please fix it. So that we can use it.

 

Thanks and Regards,

 

Mohamed Ibrahim N

**Comment by Mulham-Raee** [comment]
Dear Ibrahim,

I can't really help you of fix anything until you provide me with the code you are using at least., so I can trace the origin of the problem.

Regards

**Comment by ibrahim-appgodz** [comment]
Ok I will try to get back to you when I get the Stack Trace.

 

 

Kind Regards,

Mohamed Ibrahim N
