### ISSUE TITLE
Bug: sample has minSdk 9, while library has minSdk 14

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Mulham-Raee/Horizontal-Calendar#50]
Which of course leads to a build error.
I think it's time to update everything in the project anyway...

![image](https://user-images.githubusercontent.com/5357526/31964210-fe953ef2-b90b-11e7-866e-28ce12799295.png)

**Comment by Mulham-Raee** [comment]
Check again, Library which is (horizontalcalendar module) has minSdk 9, sample (app moudle) has minSdk 14 :)
No it is not time yet to update anything.

**Comment by AndroidDeveloperLB** [comment]
I've just cloned the entire repo at home, and got this error.
And, I still see it here on github:
https://github.com/Mulham-Raee/Horizontal-Calendar/blob/master/horizontalcalendar/build.gradle

![image](https://user-images.githubusercontent.com/5357526/31964811-fa84e298-b90d-11e7-8560-a70f4f1deedb.png)

Why can't you believe what I'm writing...

**Comment by Mulham-Raee** [comment]
your build.gradle files have been changed, I can see that they are marked blue, revert everything and try again.

**Comment by AndroidDeveloperLB** [comment]
Yes, see my updated comment.

**Comment by Mulham-Raee** [comment]
I haven't made a new release since 4 month, so I haven't updated the dependencies since then.
When I do publish a new release I will be updating them, but for now there is nothing to worry about.

**Comment by AndroidDeveloperLB** [comment]
So you shouldn't close this issue.
Google deprecated API <14 for the support libraries about 3 months ago : 

![image](https://user-images.githubusercontent.com/5357526/31965186-30238de0-b90f-11e7-8e34-931e6dee9884.png)
https://developer.android.com/topic/libraries/support-library/revisions.html

**Comment by Mulham-Raee** [comment]
Still an invalid issue, because it not relevant to the current release.
Let's say they deprecated RecyclerView, so you open an issue to delete the entire library because it not going to work if I upgraded to the new support libraries!

**Comment by AndroidDeveloperLB** [comment]
They've supported API<14 for years. 
It's time to move on. New apps won't support API<14 , and current ones will be updated to use the newest support library, which should have less issues than previous ones.
RecyclerView isn't the topic here. It's also not going to be deprecated anytime soon, as it gets updated in a repo of its own. Even ListView is still ok to be used.
