### ISSUE TITLE
Request: refactor all resources names and files, to have a prefix that's relatively unique

### ISSUE THREAD

**Issue by AndroidDeveloperLB** [Mulham-Raee/Horizontal-Calendar#51]
The purpose is to avoid overriding them by mistake.
I think that in the current repo, the only resource of this kind is "item_calendar.xml" .
Other than that, I don't think there is another one.

**Comment by Mulham-Raee** [comment]
fixed in version `1.2.5`

**Comment by AndroidDeveloperLB** [comment]
Yes, now it's hc_item_calendar.xml .
