### ISSUE TITLE
selectDate() problem

### ISSUE THREAD

**Issue by HollisCheng** [Mulham-Raee/Horizontal-Calendar#55]
horizontalCalendar.setCalendarListener-> onDateSelected function working fine

but when i using selectDate() to select the date
the date return result is correct but the selected position is -1

for example: 
selectDate(11-11-2017) 
but showing the selectedItem is (10-11-2017)
(the date return result is showing 11-11-2017<-correct

i think the problem is your position calculation wrong

**Comment by HollisCheng** [comment]
problem fixed
when you calculate the position using long time select - dateStart and the hours and mins using current
that and my select dateTime is 00:00 ,show that the result is -1 position

**Comment by anamikasingh3** [comment]
selectDate(11-11-2017) how to use this , i am unable to use dates like 11-12-2017 as selected dates , it says 
""Wrong 1st argument type. Found: 'int', required: 'java.util.Calendar' more...""
