### ISSUE TITLE
if the  datesNumberOnScreen()   set number 3  ,like this  datesNumberOnScreen(3) has some problem.

### ISSUE THREAD

**Issue by Luopan1** [Mulham-Raee/Horizontal-Calendar#57]
when datesNumberOnScreen(3),first open the application.the 207/11/02 is selected,but the toast show 2017/11/01 is selected,

**Comment by Luopan1** [comment]
i dont kown how to solve the bug,but i change your code  when i set the  datesNumberOnScreen(3),the toast and seletced is same day。here is change code.
  private void centerToPositionWithNoAnimation(final int position) {
        if (position != -1) {
            int shiftCells = numberOfDatesOnScreen / 2;
            int centerItem = calendarView.getPositionOfCenterItem();

            if (position > centerItem) {

                // TODO: 2017/11/27  changed when set datesNumberOnScreen(3)
                calendarView.scrollToPosition(position + shiftCells - 1);

            } else if (position < centerItem) {
                calendarView.scrollToPosition(position - shiftCells);
            }

            calendarView.post(new Runnable() {
                @Override
                public void run() {
                    mCalendarAdapter.notifyDataSetChanged();
                }
            });
        }
    }

**Comment by Mulham-Raee** [comment]
@Luopan1 
Thanks for your inquiry, the bug has been fixed in version `1.2.2`

Regards
