### ISSUE TITLE
How to disable dates in calendar?

### ISSUE THREAD

**Issue by sairajkishore** [Mulham-Raee/Horizontal-Calendar#59]
### Expected Behavior / Goal
> ?

### Actual Behavior
> ?

### Steps to Reproduce the Problem (sample code if possible)

  >1.
  >2.
  >3.

### Specifications

 > - Android Version:
 > - Horizontal-Calendar Version:

**Comment by Mulham-Raee** [comment]
@sairajkishore 

can you describe your problem probably? I didn't get what you want to do

**Comment by sairajkishore** [comment]
Like maxdate and mindate like date picker,all the dates above date picker
will be disabled and all dates below min date will be disabled?

**Comment by Mulham-Raee** [comment]
You can this already while initializing HorizontalCalendar by specifying `startDate` and `endDate`
do you have something else in mind?

**Comment by Mulham-Raee** [comment]
your requested feature is now available in version `1.2.5`

**Comment by MianShanni** [comment]
@Mulham-Raee  can you please tell. how can we use disable dates function. can you please provide example?
i am using this version 1.3.2

**Comment by ranaprathap2** [comment]
Ya how can we disable few dates in the range if we need!, Lets say for a week there are 5 working days , and 2 non working days... So more like I want the calendar view to enable dates that are only the working days and disable the non working days within a range between the start date and the end date .....
