### ISSUE TITLE
Cannot select the dates first dates.

### ISSUE THREAD

**Issue by tittojose** [Mulham-Raee/Horizontal-Calendar#6]
Hi,

Great work!!! 

Issue observed :
I cannot select the dates that are displayed starting.
eg : If date range is from Jan 22nd to Feb 28th, when the screen loads, by default selected date is Jan 24th and i cannot make clicks on dates Jan 22nd and Jan 23rd.

Regards,
Titto Jose.

**Comment by Mulham-Raee** [comment]
Hello Titto,

Thanks!, regarding your issue please check issue #4
