### ISSUE TITLE
V 1.3.0 gives error. (V 1.1.7 works)

### ISSUE THREAD

**Issue by ajgaurkar** [Mulham-Raee/Horizontal-Calendar#61]
I added gradle dependency and it compiles fine. But during run time this error pops up :  
**Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView**..........

.......**java.lang.ClassNotFoundException: Didn't find class "devs.mulham.horizontalcalendar.HorizontalCalendarView" on path: DexPathList**

 > - Android Version: 8.1 and 5.1.1
 > - Horizontal-Calendar Version: 1.3.0

**Comment by Mulham-Raee** [comment]
Hello @ajgaurkar,

this problem is not related to HorizontalCalendar, there is however some steps you can try to solve your issue:
1- try Clean Project & Rebuild Project.
2- clear cache and restart android studio.
3- if the above didn't work, try enabling multiDex.
