### ISSUE TITLE
Removing nonselectable dates from both sides of calendar view.

### ISSUE THREAD

**Issue by EvangelosG** [Mulham-Raee/Horizontal-Calendar#67]
### Expected Behavior / Goal
> Calendar should show starting and ending dates without adding two non-selectable dates to each side.

### Actual Behavior
> Calendar shows two extra non-selectable days. Is there a way to set the amount of non-selectable offscreen dates there are? (Ideally 0?)

### Steps to Reproduce the Problem (sample code if possible)

  >1. Just render a mapview and set any starting/ending date. You can use your sample code from the readme.
  >2.
  >3.

### Specifications

 > - Android Version:
 > - Horizontal-Calendar Version:

Side note: Thank you, thank you so much for this awesome widget. I deeply apologize if the functionality I am looking for already exists. This thing is awesome.

**Comment by Praveenmishra123** [comment]
@EvangelosG , Did you find the solution for this?. I also want to hide disabled dates.

**Comment by pratikbutani** [comment]
Any solution found for this?

**Comment by sudhirkhanger** [comment]
Did you guys find any solution for this? The non-selectable dates are highlighted whereas the selectable dates are muted which is very confusing for users.

![device-2019-03-28-090149](https://user-images.githubusercontent.com/841656/55128149-843b2d80-5138-11e9-9cef-61e16e0aa510.png)
