### ISSUE TITLE
Need to add Locales

### ISSUE THREAD

**Issue by sergon146** [Mulham-Raee/Horizontal-Calendar#7]
Add localization by Locale.getDefault() or set it manually in Builder.
But it is necessary to provide for the correct spelling of words in all languages.
For example, in Russain not "марта" and "Март" (is it March).

**Comment by Mulham-Raee** [comment]
Hello @sergon146,

Will be considered in the next release, Thanks!

**Comment by zahid--ali** [comment]
@Mulham-Raee  I want to use this library but want to represent the date in Arabic. How can I do it?
