### ISSUE TITLE
Date Range

### ISSUE THREAD

**Issue by AndileDlomo** [Mulham-Raee/Horizontal-Calendar#72]
<!---
**Feature Request**

Hi Mulham 

I am loving your library, i was hoping to find out if its possible to have a layout displaying date range starting from the current date without previous dates

**Comment by Mulham-Raee** [comment]
No description!

**Comment by AndileDlomo** [comment]
Hi Mulham

Sorry about that, I am loving your library, i was hoping to find out if its possible to have a layout displaying date range starting from the current date without previous dates showing and future date not showing. i see the horizontal layout is maintaining the previous days in the frame calendar my goal is to know if it could only maintain current day and desired end day and also is it possible to display a vertical recyclerview based on date selected by user. i.e a list of contact

**Comment by Praveenmishra123** [comment]
Hi @Mulham-Raee , Many thanks for the awesome library. How can hide the disabled dates? I want to show only date range from today onwards to the next three days. I want to hide past dates and the 2 future dates which are disabled.
