### ISSUE TITLE
Bad display of scrolling, especially on the previous date

### ISSUE THREAD

**Issue by aleksey-ho** [Mulham-Raee/Horizontal-Calendar#8]
I have downloaded the source code and I guess it because of adjustCalendarLocation method.
So I suggest remove it and add this code snippet into loadHorizontalCalendar() method

```
LinearSnapHelper snapHelper = new LinearSnapHelper();
snapHelper.attachToRecyclerView(calendarView);
calendarView.setOnFlingListener(snapHelper);
```

With this change, the display is much better

**Comment by Mulham-Raee** [comment]
Hello @aleksey-ho ,

Thanks for your helpful  suggestion, I was not aware of this helper class before 👍 .
Changes are already implemented on **version 1.1.0**
