### ISSUE TITLE
XML error !!!

### ISSUE THREAD

**Issue by drahmadfawzi** [Mulham-Raee/Horizontal-Calendar#80]
**Logcat**:
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.belk.testnew/com.belk.testnew.Activity_HzCalendar}: android.view.InflateException: Binary XML file line #9: Error inflating class devs.mulham.horizontalcalendar.HorizontalCalendarView

_what's the problem ??_
![screenshot 11](https://user-images.githubusercontent.com/35936300/38692375-ca8f7c8c-3e83-11e8-80c0-f29b6f82366d.png)

**Comment by Kamosko** [comment]
Hi, how you are solved this? Thanks

**Comment by jmcoder1** [comment]
You should say how you solved it. I have the same problem and I'm sure I am not the only one.

**Comment by jmcoder1** [comment]
> 
> 
> Hi, how you are solved this? Thanks

Did you figure it out?
